@startuml listRobotSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}


box "<<RobDroneGo(C4)>>\n\tSystem"

participant CampusManagement as CM <<Container(C4)>>
end box

-> CM: GET GetAll()
activate CM

alt If there are available Robot
 <-- CM : 200 OK


else If there are no Robot in the system

 <-- CM : 404 NOT FOUND
deactivate CM


end


@enduml