@startuml createElevadorSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}


!pragma teoz true
box "<<Container(C4)>>\n Campus Management" #LightGreen

    box "<<Component(C4)>>\nInterface Adapter Layer" #Cyan
        participant IElevadorController as  ICTL <<Component(C4)>>
        participant ElevadorController as  CTL <<Component(C4)>>
        participant ElevadorRepository as  DR <<Component(C4)>>
    end box
      box "<<Component(C4)>>\nApplication Services Layer" #Red
        participant ElevadorService as  SV <<Component(C4)>>
        participant IElevadorService as  ISV <<Component(C4)>>
        participant IElevadorRepo as  IER <<Component(C4)>>
      end box
      box "<<Component(C4)>>\nEntities\Core\Domanin Layer" #Yellow
        participant "Elevador : Elevador" as  elevador <<Component(C4)>>
      end box
participant "ElevadorDTO : ElevadorDTO" as  DTO <<Component(C4)>>

end box


 -> CTL: POST Post(ElevadorDto)
alt If the Elevador doesn't exist in the system
activate CTL
CTL -> SV : CreateElevador(ElevadorDto)
activate SV

SV -> elevador : Create(ElevadorDto)
activate elevador
elevador --> SV : Elevador
deactivate elevador

SV -> DR : save(Elevador)
activate DR
DR --> SV : true
deactivate DR

SV -> DTO : toElevadorDTO(elevador)
activate DTO
DTO --> SV : ElevadorDto
deactivate DTO
SV --> CTL : ElevadorDto
deactivate SV
 <-- CTL : ElevadorDto

 <-- CTL: 200 OK
deactivate CTL





else If a Elevador already exists with the id entered




CTL -> SV : CreateElevador(ElevadorDto)
activate CTL
activate SV

SV -> elevador : Create(ElevadorDto)
activate elevador
elevador --> SV : Elevador
deactivate elevador

SV -> DR : save(Elevador)
activate DR
DR --> SV : false
deactivate DR
SV --> CTL : BadRequestException
deactivate SV
 <-- CTL : BadRequestException


 <-- CTL: 400 BAD REQUEST
deactivate CTL




else If the attributes do not respect the business rules


CTL -> SV : CreateElevador(ElevadorDto)
activate CTL
activate SV

SV -> elevador : Create(ElevadorDto)
activate elevador
elevador --> SV : BusinessRuleValidationException
deactivate elevador

SV --> CTL : BusinessRuleValidationException
deactivate SV
 <-- CTL : BusinessRuleValidationException

 <-- CTL: 400 BAD REQUEST
deactivate CTL


end

@enduml