@startuml updatePisoSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}


!pragma teoz true
box "<<System(C4)>>\n RobDroneGo" #LightSkyBlue
    box "<<Container(C4)>>\n Campus Management" #LightGreen

        box "<<Component(C4)>>\nInterface Adapter Layer" #Cyan
            participant IPisoController as  ICTL <<Component(C4)>>
            participant PisoController as  CTL <<Component(C4)>>
            participant PisoRepository as  DR <<Component(C4)>>
        end box
        box "<<Component(C4)>>\nApplication Services Layer" #Red
            participant PisoService as  SV <<Component(C4)>>
            participant IPisoService as  ISV <<Component(C4)>>
            participant IPisoRepo as  IER <<Component(C4)>>
        end box
        box "<<Component(C4)>>\nEntities\Core\Domanin Layer" #Yellow
            participant "Piso : Piso" as  Piso <<Component(C4)>>
        end box
    participant "PisoDTO : PisoDTO" as  DTO <<Component(C4)>>

    end box
end box


 -> CTL: PUT Put(PisoDto)
 activate CTL
alt If the Piso exists in the system


    CTL -> SV : UpdatingPiso(PisoDto)
    activate SV
    

    SV -> DR: GetByID(PisoId)
    activate DR
    DR --> SV: Piso
    deactivate DR

    SV -> Piso : Update(PisoDTO)
    activate Piso
    Piso --> SV : Piso
    deactivate Piso

    SV -> DR : save(Piso)
    activate DR
    DR --> SV : true
     deactivate DR
    SV -> DTO : toPisoDTO(Piso)
    activate DTO
    DTO -> DTO: toDTO(Piso)
    
    DTO --> SV : PisoDTO
    deactivate DTO
    SV -> CTL : PisoDTO
    deactivate SV
     <-- CTL : PisoDto + 200 OK
     deactivate CTL




else If a Piso already exists with the id entered




CTL -> SV : CreatePiso(PisoDto)
activate CTL
activate SV

SV -> Piso : Create(PisoDto)
activate Piso
Piso --> SV : Piso
deactivate Piso

SV -> DR : save(Piso)
activate DR
DR --> SV : false
deactivate DR
SV --> CTL : BadRequestException
deactivate SV
 <-- CTL : BadRequestException


 <-- CTL: 400 BAD REQUEST
deactivate CTL




else If the attributes do not respect the business rules


CTL -> SV : CreatePiso(PisoDto)
activate CTL
activate SV

SV -> Piso : Create(PisoDto)
activate Piso
Piso --> SV : BusinessRuleValidationException
deactivate Piso

SV --> CTL : BusinessRuleValidationException
deactivate SV
 <-- CTL : BusinessRuleValidationException

 <-- CTL: 400 BAD REQUEST
deactivate CTL


end

@enduml