@startuml listEdificioSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}



!pragma teoz true
box "<<System(C4)>>\n RobDroneGo" #LightSkyBlue
    box "<<Container(C4)>>\n Campus Management" #LightGreen

        box "<<Component(C4)>>\nInterface Adapter Layer" #Cyan
            participant IEdificioController as  ICTL <<Component(C4)>>
            participant EdificioController as  CTL <<Component(C4)>>
            participant EdificioRepository as  DR <<Component(C4)>>
        end box
        box "<<Component(C4)>>\nApplication Services Layer" #Red
            participant EdificioService as  SV <<Component(C4)>>
            participant IEdificioService as  ISV <<Component(C4)>>
            participant IEdificioRepo as  IER <<Component(C4)>>
        end box
        box "<<Component(C4)>>\nEntities\Core\Domanin Layer" #Yellow
            participant "Edificio : Edificio" as  edificio <<Component(C4)>>
        end box
    participant "EdificioDTO : EdificioDTO" as  DTO <<Component(C4)>>

    end box
end box   



 -> CTL: GET getAllEdificio()
activate CTL
alt If there are Edificio on the system


    CTL -> SV : getAllEdificio()
    activate SV

    SV -> DR : getAll()
    activate DR

    DR --> SV : EdificioList
    deactivate DR


    SV -> DTO : toDTO(EdificioList)
    activate DTO 
    DTO -> DTO: toDTO(EdificioList)
    DTO --> SV : List
    deactivate DTO
    deactivate DR
    SV --> CTL: List
    deactivate SV

     <-- CTL: 200 OK + List
    deactivate CTL

else If there are no Edificio on the system
    
    
    CTL -> SV : getAllEdificio() 
    activate SV
    activate CTL
    
  

    
    SV -> DR : getAll()
    activate DR

    DR -> SV : null
    deactivate DR

    SV --> CTL : null
    deactivate SV
     <-- CTL: 200 OK + null (empty List)
    deactivate CTL

    
   



end

@enduml
